### ISSUE TITLE
Processing builds on OS X fails due to: KeyError: u'macosx64'

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#651]
Looks like my refactoring as done in  PR #648 caused triggering of builds on OS X to fail:

> 2015-09-23T12:14:52Z ERROR mozmill-ci: Failed to process Mozilla Pulse message.
Traceback (most recent call last):
  File "/data/mozmill-ci/lib/queues.py", line 74, in process_message
    self._on_message(preprocessed_body)
  File "/data/mozmill-ci/lib/queues.py", line 143, in _on_message
    self.callback(**build_properties)
  File "./pulse.py", line 245, in process_build
    for node in tree_config['nodes'][platform_id]:
KeyError: u'macosx64'

**Comment by whimboo** [comment]
Really a silly mistake which I made here:
https://github.com/mozilla/mozmill-ci/pull/648/files#diff-3f4f7efcc168c2effa484018e5d487bbR172

Instead of passing in platform as string it has to be the real value. PR coming up in a moment.

**Comment by whimboo** [comment]
PR #652 got merged. I will push immediately to staging and maybe later to production.
