### ISSUE TITLE
Config misses win64 entry for mozilla-esr45 branch

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#771]
2016-03-16T11:13:42Z ERROR mozmill-ci: Failed to process Mozilla Pulse message.
Traceback (most recent call last):
  File "/data/mozmill-ci/lib/queues.py", line 77, in process_message
    self._on_message(preprocessed_body)
  File "/data/mozmill-ci/lib/queues.py", line 147, in _on_message
    self.callback(**build_properties)
  File "/data/mozmill-ci/lib/automation.py", line 352, in process_build
    for node in tree_config['nodes'][platform_id]:
KeyError: u'win64'

**Comment by whimboo** [comment]
PR #772 got merged and will be deployed in the next hours.
