### ISSUE TITLE
funsize update message fail to process

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#800]
Looks like we fail to process funsize update messages on mozmill-ci staging. Maybe this is related to my taskcluster changes as landed earlier today.

> 2016-06-30T15:04:02Z DEBUG mozmill-ci: Found routing key: route.index.funsize.v1.mozilla-central.latest.win32.2.4_1.balrog
2016-06-30T15:04:02Z DEBUG taskcluster.baseclient: credentials key scrubbed from logging output
2016-06-30T15:04:02Z DEBUG taskcluster.baseclient: {'maxRetries': 5, 'baseUrl': 'https://queue.taskcluster.net/v1', 'signedUrlExpiration': 900}
2016-06-30T15:04:02Z ERROR mozmill-ci: Failed to process Mozilla Pulse message.
Traceback (most recent call last):
  File "/data/mozmill-ci/lib/queues.py", line 91, in process_message
    preprocessed_body = self._preprocess_message(body, message)
  File "/data/mozmill-ci/lib/queues.py", line 279, in _preprocess_message
    'public/env/manifest.json')
  File "/data/mozmill-ci/jenkins-env/lib/python2.7/site-packages/taskcluster/baseclient.py", line 177, in buildUrl
    for key, value in six.iteritems(replDict):
  File "/data/mozmill-ci/jenkins-env/lib/python2.7/site-packages/six.py", line 599, in iteritems
    return d.iteritems(**kw)
AttributeError: 'str' object has no attribute 'iteritems'

**Comment by whimboo** [comment]
This looks to be a regression from the taskcluster client version bump. Something has been changed in the `buildUrl()` method. I can reproduce this with:

> import taskcluster
q = taskcluster.Queue()
q.buildUrl('getLatestArtifact', 'XYm7yDlZTOaytE-FQ9dtcA', 'public/manifest.json')

Ccing @djmitche for information.

**Comment by jhford** [comment]
can you please give provide the URL that it used to provide and what it does now?

**Comment by jhford** [comment]
oh it's an exception!  silly me.

**Comment by whimboo** [comment]
So we bumped from taskcluster==0.0.24 to 0.3.4. It's a kinda large range.

**Comment by whimboo** [comment]
What I can use instead would be:

> q.getLatestArtifact('XYm7yDlZTOaytE-FQ9dtcA', 'public/env/manifest.json')

I think its better ot get rid of the requests module here and directly use the tc client methods now. Maybe those weren't available with version 0.0.24.

**Comment by jhford** [comment]
The buildUrl and buildSignedUrl functions were broken during the py3 and async patches.  I missed that during review and now they don't make any sense.  I'll open a bug for that.

**Comment by jhford** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1283516

**Comment by whimboo** [comment]
PR #801 fixed the problem on staging. I will push it to production together with the other tc changes which caused this regression.
